---
name: khatgallery
version: 0.02
author:
  - Kathryn Andersen
abstract: HTML photo album generator.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Cwd: 3
  File::Basename: 2.73
  File::Spec: 3
  File::stat: 1
  Getopt::ArgvFile: 1.09
  Getopt::Long: 2.34
  Image::Info: 1.16
  Image::Magick: 6.2
  POSIX: 0
  Pod::Usage: 0
  YAML: 0.35
build_requires:
  Test::More: 0
provides:
  HTML::KhatGallery:
    file: lib/HTML/KhatGallery.pm
    version: 0.02
  HTML::KhatGallery::Core:
    file: lib/HTML/KhatGallery/Core.pm
    version: 0.02
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
